### PR TITLE
WIP - Change site for 2019

### PR DESCRIPTION
**Pull request by Dzol**
I can't test this locally as Ruby won't work on my machine but will ask Nasreen to help this evening.

A few things we've gotta do:

- [x] grant me elevated permision on the GitHub organization - I can't fork the site to keep the 2018 version under this organization
- [x] get me (or all of us) behind the @enthusiasticon.de addresses [keeping track of this elsewhere]
- [x] review the above [Nasreen & I checked this on her machine]

This is work toward #22 and #23 .

### CODE REVIEW

**Comment by hellerve** [comment]
The above seems fine, but as for points 1 and 2 I think @zormit is the only one who has privileges here. Would you be able to fulfill @Dzol’s request?

**Comment by zormit** [comment]
done. I can also provide the 2018.enthusiasticon subdomain of course. sorry for being super unresponsive lately.

**Comment by hellerve** [comment]
No problem at all! Thanks for inviting me to the organization!

**Comment by Dzol** [comment]
Thanks!

**Comment by Dzol** [comment]
I'm merging this, I'll inspect for anything we may have overlooked, and correct anything in another PR

**Pull request merged**
