### PR TITLE
Introduce a Programme Page

### PR DESCRIPTION
**Pull request by Dzol**
I formatted the table as nice as I could: not sure how to get it better... CSS?

### CODE REVIEW

**Comment by hellerve** [comment]
Before we merge this I would like to give styling it a stab!

**Comment by hellerve** [comment]
Done with initial styling, reformatted a bit, and fixed a typo. Any feedback welcome!

**Comment by zormit** [comment]
regarding styling: I like it better. It bothers me a bit that rows of the different blocks are not horizontally aligned, but it's acceptable :)

I did push another change, I think the HH:MM format is more common. Is that okay?

Also I thought it's more logical to include the breaks in the "header timerange" (e.g. "Arrival & Keynote" ends at 11:15, after the break). Now that I'm writing this I'm not so sure anymore which is more clear xD.

**Comment by Dzol** [comment]
It looks much better now :)

**Comment by hellerve** [comment]
I’m quite passionless about the time format and header timerange; whatever y’all like better we can keep.

Yeah, I looked at the blocks as well. We could probably set a `max-width` for the first `td`, but I’m not sure that’s responsive.

**Comment by zormit** [comment]
More suggestions for change, I thought we could add "Block Titles" for the four blocks. What do you think about:

1. From IDEAs to Joy
2. The Power of Language
3. Hands On, Embrace the Theory
4. Shaping Your Environment

?

**Comment by hellerve** [comment]
I’m not a big fan of any of those. Why do we need titles for the blocks? It seems like then we’re restraining the talks by giving the audience ideas about what they’re supposed to be, at least in a category sense, which I find highly unfair.

**Comment by zormit** [comment]
Makes sense! Not needed, it was just an attempt to summarize how I grouped the talks with an amusing phrase. But you're right, it's probably unneccesarily inducing expectations.

**Comment by hellerve** [comment]
Is this mergeable, then?

**Comment by zormit** [comment]
I added speaker names. If this looks okay to you, please merge. If it's too much information duplication, we can also go without the names.

**Comment by hellerve** [comment]
LGTM :+1:

**Pull request merged**
