### PR TITLE
WIP - Introduce table w/ cost detail - most still remaining

### PR DESCRIPTION
**Pull request by Dzol**
A potential sponsor asked for more detail - as they should expect. I'm working on the exact numbers. We should have them by EOD tomorrow.

### CODE REVIEW

**Comment by hellerve** [comment]
I think website will probably be `€0`, right (except the domain name)?

**Comment by Dzol** [comment]
Hey, can we take one more look at this before I point people to it again? There's not much here. I just want to make sure at least one other person sees the changes.

**Comment by hellerve** [comment]
If we want VOC recording we will need to insure the equipment. [This](https://www.erpam.com/i/elektronikversicherung_kurzfristig) was recommended to me by another person, meaning it will be probably around €120 for a day. Do we still want to have our talks recorded by the VOC this time? If so, we’ll have to  factor that in.

**Comment by Dzol** [comment]
What's VOC?

> Do we still want to have our talks recorded by the VOC this time?

I'd guess "yes", assuming this is closest to what we did last year, as I'm not sure how much we can rely on the AV at the space, tho it was pretty good last year IIRC. The other argument I see in favour, is that it'd be closest to what we had last year in terms of what the video/recording is like... since the 2018 video/recording turned out so good, shall we stick to what we know for 2019?

**Comment by hellerve** [comment]
VOC is the is [CCC Video Operation Center](https://c3voc.de/). We contacted them last year as well, and we briefly talked about having them do the recordings this year during our last meeting. I’m all for using the venue’s recording capabilities because we don’t need to organize anything for that then, but the quality of their—meaning the VOC—recordings will definitely be better than the venue’s.

**Comment by Dzol** [comment]
I see... do we have to pay for _using_ their equipment too? I think we'll be able to get sponsorship to cover this too so it's worth a shot IMO. I've updated the list: is there anything else we're missing?

**Comment by hellerve** [comment]
No, we don’t, but we still have to apply and organize everything.

Apart from that, I can’t think of anything that’s missing! :)

**Comment by Dzol** [comment]
> we still have to apply and organize everything

I guess we can make way on this this week

**Pull request merged**
